// Generated by generate_frontend_constants.py — do not hand-edit.
// Re-run the script after the legacy aggregate changes.
//
// The legacy data covers only a small subset of the country, and it is filtered
// by full name rather than by the id/code used elsewhere in constants/ — the
// legacy_location_stats table stores names only. Drive the cascading filters
// from this tree so the UI can never offer a combination that returns zero rows.

export interface LegacyDistrict {
  district: string;
  mandals: string[];
}

export interface LegacyState {
  state: string;
  districts: LegacyDistrict[];
}

export const LEGACY_LOCATIONS: LegacyState[] = [
  {
    state: "Andhra Pradesh",
    districts: [
      {
        district: "Tirupati",
        mandals: [
          "Buchinaidu Kandriga",
          "Chandragiri",
          "Chinnagottigallu",
          "Dakkili",
          "K.V.B.Puram",
          "Nagalapuram",
          "Narayanavanam",
          "Pakala",
          "Pichatur",
          "Puttur",
          "Ramachandrapuram",
          "Renigunta",
          "Satyavedu",
          "Srikalahasti",
          "Thottambedu",
          "Tirupati Rural",
          "Tirupati Urban",
          "Vadamalapeta",
          "Varadaiahpalem",
          "Yerpedu",
          "Yerravaripalem",
        ],
      },
    ],
  },
  {
    state: "Telangana",
    districts: [
      {
        district: "Hyderabad",
        mandals: [
          "Musheerabad",
        ],
      },
    ],
  },
  {
    state: "Unknown",
    districts: [
      {
        district: "Unknown",
        mandals: [
          "Unknown",
        ],
      },
    ],
  },
];
